---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-gogs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-sonar-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
